name: Integration Test

on:
  push:
    paths-ignore:
      - "**.md"

# TODO: Add new job 'install-and-run-stable-property4win' (it use `install.ps1`)
#       like https://github.com/rnazmo/property/blob/main/.github/workflows/integ-test.yml

jobs:
  run-head-property4win:
    name: Run property4win (HEAD version)
    strategy:
      matrix:
        # Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
        # pwsh: PowerShell Core
        # pwsh: PowerShell DeskTop
        shell: [pwsh, powershell]
    runs-on: windows-latest
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Print working directory
        run: pwd
      - name: ls
        run: ls
      - name: Print PowerShell Edition/Version
        run: $PSVersionTable
      - name: Run property4win
        run: .\property4win
